# Reference files are generated by validation/multicomponent_reference.py.
# CANTERA_MULTICOMPONENT_REFERENCE points to the generated directory.
using Test, Arrhenius, LinearAlgebra, NPZ
if !isdefined(Arrhenius,:MultiTransportData)
    Base.include(Arrhenius,joinpath(@__DIR__,"..","src","MulticomponentTransport.jl"))
end
@testset "multicomponent transport input checks" begin
    if haskey(ENV,"CANTERA_MULTICOMPONENT_REFERENCE")
        path=joinpath(ENV["CANTERA_MULTICOMPONENT_REFERENCE"],"h2o2-transport.npz")
        data=Arrhenius.MultiTransportData(path)
        w=Arrhenius.MultiTransportWorkspace(data)
        n=length(data.molecular_weights)
        X=fill(1/n,n); cp=fill(3.5,n)
        @test_throws ArgumentError Arrhenius.multicomponent_transport!(w,data,-1.,300.,X,cp)
        @test_throws ArgumentError Arrhenius.multicomponent_transport!(w,data,101325.,NaN,X,cp)
        @test_throws ArgumentError Arrhenius.multicomponent_transport!(w,data,101325.,300.,zeros(n),cp)
        @test_throws DimensionMismatch Arrhenius.multicomponent_transport!(w,data,101325.,300.,X[1:end-1],cp)
        # Regression includes NASA heat capacities from the native gas overload.
        mechanism=joinpath(ENV["CANTERA_MULTICOMPONENT_REFERENCE"],"h2o2.yaml")
        if isfile(mechanism*".npz")
            gas=CreateSolution(mechanism)
            data=Arrhenius.MultiTransportData(path,gas)
            ref=npzread(joinpath(ENV["CANTERA_MULTICOMPONENT_REFERENCE"],"h2o2-reference.npz"))
            for k in (1,7,13,19)
                P,T=ref["P"][k],ref["T"][k]
                X=vec(ref["X"][k,:])
                lambda=Arrhenius.multicomponent_transport!(w,data,gas,P,T,X)
                @test lambda ≈ ref["conductivity"][k] rtol=1e-11
                @test w.thermal_diffusion ≈ ref["thermal_diffusion"][k,:] rtol=1e-10 atol=1e-16
                @test w.diffusion ≈ ref["diffusion"][k,:,:] rtol=1e-11
            end
        end
    else
        @test_skip false
    end
end
